name: Bug Report
description: Report a bug in openleash
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A clear, concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the behavior.
      placeholder: |
        1. Run `npx openleash start`
        2. Send a request to ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: "Output of `npx openleash --version` or the package version."
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS
      description: "Operating system and version."
      placeholder: "macOS 15.2 / Ubuntu 24.04 / Windows 11"
    validations:
      required: false
