name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A brief description of the feature you'd like.
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? What's the use case?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How do you think this should work?
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative approaches you've thought about.
    validations:
      required: false
